-- Entity registry: types, fields, JSONB records (clean rebuild)

create table if not exists public.entity_types (
  id uuid primary key default gen_random_uuid(),
  slug text not null unique,
  name text not null,
  description text,
  icon text default 'prime:box',
  category text not null default 'custom',
  is_scoped boolean not null default true,
  created_by uuid references auth.users (id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint entity_types_slug_format check (slug ~ '^[a-z][a-z0-9_-]{0,62}$')
);

create table if not exists public.entity_fields (
  id uuid primary key default gen_random_uuid(),
  entity_type_id uuid not null references public.entity_types (id) on delete cascade,
  name text not null,
  label text not null,
  field_type text not null default 'input-text',
  sort_order int not null default 0,
  required boolean not null default false,
  show_in_table boolean not null default true,
  show_in_form boolean not null default true,
  options jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (entity_type_id, name),
  constraint entity_fields_name_format check (name ~ '^[a-z][a-z0-9_]{0,62}$')
);

create table if not exists public.entity_records (
  id bigint generated by default as identity primary key,
  entity_type_id uuid not null references public.entity_types (id) on delete cascade,
  user_id uuid references auth.users (id) on delete set null,
  data jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists entity_records_type_user_idx
  on public.entity_records (entity_type_id, user_id);

create index if not exists entity_records_data_gin
  on public.entity_records using gin (data);

create index if not exists entity_fields_type_sort_idx
  on public.entity_fields (entity_type_id, sort_order);

alter table public.entity_types enable row level security;
alter table public.entity_fields enable row level security;
alter table public.entity_records enable row level security;

-- Gateway uses service role; policies for direct client access if needed
drop policy if exists entity_types_owner_all on public.entity_types;
create policy entity_types_owner_all on public.entity_types
  for all to authenticated
  using (created_by = auth.uid())
  with check (created_by = auth.uid());

drop policy if exists entity_fields_via_type on public.entity_fields;
create policy entity_fields_via_type on public.entity_fields
  for all to authenticated
  using (
    exists (
      select 1 from public.entity_types t
      where t.id = entity_type_id and t.created_by = auth.uid()
    )
  )
  with check (
    exists (
      select 1 from public.entity_types t
      where t.id = entity_type_id and t.created_by = auth.uid()
    )
  );

drop policy if exists entity_records_scoped on public.entity_records;
create policy entity_records_scoped on public.entity_records
  for all to authenticated
  using (
    user_id = auth.uid()
    or exists (
      select 1 from public.entity_types t
      where t.id = entity_type_id and t.is_scoped = false and t.created_by = auth.uid()
    )
  )
  with check (
    user_id = auth.uid()
    or exists (
      select 1 from public.entity_types t
      where t.id = entity_type_id and t.is_scoped = false and t.created_by = auth.uid()
    )
  );
