create table if not exists public.articles (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users (id) on delete set null,
  title text not null,
  description text not null,
  category text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- Legacy tables without user_id skip CREATE TABLE; indexes must still see user_id.
alter table public.articles add column if not exists user_id uuid references auth.users (id) on delete set null;

create table if not exists public.contacts (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users (id) on delete set null,
  first_name text not null,
  last_name text,
  email text,
  personal_phone text,
  work_phone text,
  address text,
  birthday date,
  contact_groups jsonb default '[]'::jsonb,
  role text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.contacts add column if not exists user_id uuid references auth.users (id) on delete set null;

create table if not exists public.money (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users (id) on delete set null,
  sender text not null,
  receiver text not null,
  count integer not null default 0,
  title text not null,
  description text,
  category text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.money add column if not exists user_id uuid references auth.users (id) on delete set null;

create index if not exists articles_user_id_idx on public.articles (user_id);
create index if not exists contacts_user_id_idx on public.contacts (user_id);
create index if not exists money_user_id_idx on public.money (user_id);

alter table public.articles enable row level security;
alter table public.contacts enable row level security;
alter table public.money enable row level security;

drop policy if exists "entities_articles_authenticated_all" on public.articles;
create policy "entities_articles_authenticated_all" on public.articles for all to authenticated using (true) with check (true);
drop policy if exists "entities_contacts_authenticated_all" on public.contacts;
create policy "entities_contacts_authenticated_all" on public.contacts for all to authenticated using (true) with check (true);
drop policy if exists "entities_money_authenticated_all" on public.money;
create policy "entities_money_authenticated_all" on public.money for all to authenticated using (true) with check (true);
